version: 2.1

orbs:
  go: circleci/go@1.11.0

jobs:
  build-and-deploy:
    docker:
      - image: cimg/go:1.21.3
    steps:
      - checkout
      - run: go version
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Build binary
          command: |
            cd ./cmd
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-extldflags=-static" -o junosOps
            mv junosOps ../../bin
      - run:
          name: List bin directory contents
          command: ls -al ~/bin
      - run:
          name: Install GitHub CLI
          command: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/githubcli.list > /dev/null
            sudo apt update
            sudo apt install gh
      - run:
          name: Verify binary before upload
          command: |
            if [ ! -f ~/bin/junosOps ]; then
              echo "Binary file not found!"
              exit 1
            fi
            echo "Binary file found. Proceeding with release."
      - run:
          name: Upload binary to GitHub Release
          command: |
            VERSION=$(git describe --tags --always --dirty="-dev" 2>/dev/null)
            if [ -z "$VERSION" ]; then
              VERSION="v0.1.0"
            fi
            echo "Releasing $VERSION"
            echo $GITHUB_TOKEN | gh auth login --with-token
            gh release create $VERSION ~/bin/junosOps --title "junosOps $VERSION" --notes "Automated release from CircleCI"

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
