version: 2.1

orbs:
  go: circleci/go@1.11.0

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.21.3
    steps:
      - checkout
      - run: go version
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Build binary
          command: |
            cd ./cmd
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-extldflags=-static" -o port-audit
      - run:
          name: Move binary to artifacts directory
          command: mv port-audit ~/bin/
      - store_artifacts:
          path: ~/bin
          destination: executables

  deploy:
    docker:
      - image: cibuilds/github:1.29.0
    steps:
      - checkout
      - run:
          name: Upload binary to GitHub Release
          command: |
            VERSION=$(git describe --tags)
            if [ -z "$VERSION" ]; then
              VERSION="v0.1.0"
            fi
            echo "Releasing $VERSION"
            gh release create $VERSION ~/artifacts/port-audit --title "$VERSION" --notes "Automated release from CircleCI"

workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
