version: 2.1

orbs:
  go: circleci/go@1.11.0
  github-cli: circleci/github-cli@2.0

jobs:
  build-and-deploy:
    docker:
      - image: cimg/go:1.21.3
    working_directory: ~/project
    steps:
      - checkout
      - run: go version
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Build binary
          command: |
            mkdir -p ~/project/bin
            cd ./cmd
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-extldflags=-static" -o ../bin/junosOps
      - run:
          name: Move binary to artifacts directory
          command: mv junosOps ~/project/bin/
      - store_artifacts:
          path: ~/project/bin/junosOps
          destination: executables
      - github-cli/install
      - run:
          name: Upload binary to GitHub Release
          command: |
            VERSION=$(git describe --tags --always --dirty="-dev" 2>/dev/null)
            if [ -z "$VERSION" ]; then
              VERSION="v0.1.0"
            fi
            echo "Releasing $VERSION"
            echo $GITHUB_TOKEN | gh auth login --with-token
            gh release create $VERSION ~/project/bin/junosOps --title "junosOps $VERSION" --notes "Automated release from CircleCI"
          environment:
            GITHUB_TOKEN: $GITHUB_TOKEN

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
