version: 2.1

orbs:
  go: circleci/go@1.11.0
  gh: circleci/github-cli@2.2.0

jobs:
  build-and-deploy:
    docker:
      - image: cimg/go:1.21.3
    steps:
      - checkout
      - run: go version
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Build binary
          command: |
            cd ./cmd
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-extldflags=-static" -o junosOps
            mv junosOps ../../bin
      - run:
          name: Create bin directory
          command: mkdir -p ~/project/bin
      - run:
          name: Move binary to bin directory
          command: mv ./bin/junosOps ~/project/bin/
      - run:
          name: List bin directory contents
          command: ls -al ~/project/bin
      - gh/setup:
          token: GITHUB_TOKEN
      - run:
          name: Verify binary before upload
          command: |
            if [ ! -f ~/project/bin/junosOps ]; then
              echo "Binary file not found!"
              exit 1
            fi
            echo "Binary file found. Proceeding with release."
      - run:
          name: Upload binary to GitHub Release
          command: |
            VERSION=$(git describe --tags --always --dirty="-dev" 2>/dev/null)
            if [ -z "$VERSION" ]; then
              VERSION="v0.1.0"
            fi
            echo "Releasing $VERSION"
            gh release create $VERSION ~/project/bin/junosOps --title "junosOps $VERSION" --notes "Automated release from CircleCI"

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
